//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddInfaormation
    {
        public int id { get; set; }
        public int UserID { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int PasportSeries { get; set; }
        public int PasportNumber { get; set; }
        public string Guid { get; set; }
        public string Ein { get; set; }
        public string SocialType { get; set; }
        public byte[] Birthdate { get; set; }
        public int SocialSecNumber { get; set; }
    
        public virtual User User { get; set; }
    }
}
