//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Ne_navredyEntities : DbContext
    {
        private static Ne_navredyEntities _context;
        public Ne_navredyEntities()
            : base("name=Ne_navredyEntities")
        {
        }

        public static Ne_navredyEntities GetContext()
        {
            if (_context == null)
            {
                _context = new Ne_navredyEntities();
            }
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddInfaormation> AddInfaormation { get; set; }
        public virtual DbSet<Authorization> Authorization { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrdersServices> OrdersServices { get; set; }
        public virtual DbSet<Organization> Organization { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UsersServices> UsersServices { get; set; }
    }
}
