//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersServices
    {
        public int id { get; set; }
        public int OrderID { get; set; }
        public int ServiceID { get; set; }
        public int StatusID { get; set; }
        public int MachineNumber { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Service Service { get; set; }
        public virtual Status Status { get; set; }
    }
}
