//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public int id { get; set; }
        public int UserID { get; set; }
        public string Country { get; set; }
        public string Address { get; set; }
        public int BIK { get; set; }
        public int INN { get; set; }
        public string Name { get; set; }
        public string UA { get; set; }
        public string PC { get; set; }
    
        public virtual User User { get; set; }
    }
}
